export const list_team_members = [
  {
    id: 1,
    username: "Sambhav Saxena",
    image: "/team/me.jpeg",
    dis: "The idea of an open source community within an institution is itself so readily acceptable by everyone we have been talking to, why not just implement the same in actual? Just thought.",
    link: "https://github.com/sambhavsaxena",
    post: "Nobody",
    isFront: true,
  },
  {
    id: 2,
    username: "Rahul",
    image: "/team/rahul.jpg",
    dis: "Working around with different kinds of ML Algorithms and coming to an actual solution was almost impossible without having a community behind my back.",
    link: "https://github.com/ErRahul001",
    post: "Operations Lead",
    isFront: false,
  },
  {
    id: 3,
    username: "Aryan Sanghi",
    image: "/team/sanghi.png",
    dis: "After working with a lot of professionals from not just from India but from around the planet, I realized the power of a community by actually being a part of one. Hence this.",
    link: "https://github.com/Aryan-Sanghi-008",
    post: "Competitive Programmer",
    isFront: true,
  },
  {
    id: 4,
    username: "Teesha Kukal",
    image: "/team/teesha.jpg",
    dis: "After working with a lot of professionals from not just from India but from around the planet, I realized the power of a community by actually being a part of one. Hence this.",
    link: "https://github.com/teesha809",
    post: "Data Analyst",
    isFront: false,
  },
  {
    id: 5,
    username: "Ansal Jain",
    image: "/team/ansal.jpg",
    dis: "After working with a lot of professionals from not just from India but from around the planet, I realized the power of a community by actually being a part of one. Hence this.",
    link: "https://github.com/jainansal",
    post: "Competitive Programmer",
    isFront: true,
  },
  {
    id: 6,
    username: "Srishti Madaan",
    image: "/team/srish.jpg",
    dis: "From learning core ECE subjects and development side by side, I have come a long way and it's the community that has held me back so far. So why not disseminate back to it?",
    link: "https://github.com/srish-03",
    post: "Fullstack developer",
    isFront: false,
  },
  {
    id: 7,
    username: "Harsh Prajapati",
    image: "/team/gola.jpeg",
    dis: "After working with a lot of professionals from not just from India but from around the planet, I realized the power of a community by actually being a part of one. Hence this.",
    link: "https://github.com/pardhan007",
    post: "Web Developer",
    isFront: false,
  },
  {
    id: 8,
    username: "Himanshu",
    image: "/team/himanshu.jpeg",
    dis: "After working with a lot of professionals from not just from India but from around the planet, I realized the power of a community by actually being a part of one. Hence this.",
    link: "https://github.com/Himanshu-Rishi",
    post: "Web Developer",
    isFront: false,
  },
  {
    id: 9,
    username: "Parikshit Verma",
    image: "/team/pari.jpeg",
    dis: "After working with a lot of professionals from not just from India but from around the planet, I realized the power of a community by actually being a part of one. Hence this.",
    link: "https://github.com/parik-shit",
    post: "Blockchain Developer",
    isFront: false,
  },
];

export const list_FAQ = [
  {
    id: 1,
    title: "What exactly is open source?",
    desc: "Open source is something that has been and can be developed and used by anyone without any restrictions.",
  },
  {
    id: 2,
    title: "Why are we here?",
    desc: "We, the students of DCRUST, are here to help the community grow learn more about open source contributing to it.",
  },
  {
    id: 3,
    title: "What are we doing currently?",
    desc: "We are working to develop an entirely new way of learning about open source. A space to learn everything maybe.",
  },
  {
    id: 4,
    title: "What can I expect from DCRUSTODC?",
    desc: "A deeper knowledge of the community, a better understanding of contributions, of Github, and a better understanding of huge codebases.",
  },
  {
    id: 5,
    title: "Where can I start?",
    desc: "Start by browsing over the Github projects, opening issues, merging PRs, and more, to know the basics and start from absolute beginning, you can join our discord server and clear things out.",
  },
  {
    id: 6,
    title: "Can I join the community with no knowledge about programming?",
    desc: "Yes, not just this, but any other open source community is equally welcoming and beginner friendly for people of all domains.",
  },
];
